---
title: "Project 8"
output:
  pdf_document: 
    extra_dependencies: ['amsmath']
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE, warning=FALSE, message=FALSE)
```

# Problem 20

## Construction of transitive closure

```{r}
phi1 <- diag(5)
rownames(phi1) <- paste0("S", 1:5)
colnames(phi1) <- paste0("S", 1:5)
phi1["S1","S3"] <- 1
phi1["S1","S4"] <- 1
phi1["S2","S5"] <- 1
phi1["S3","S4"] <- 1
phi1["S3","S5"] <- 1
phi1["S4","S5"] <- 1

phi1 <- phi1 + phi1 %*% phi1
phi1 <- apply(phi1, c(1, 2), function(x) min(x, 1))
phi1
```

```{r}
phi2 <- diag(5)
rownames(phi2) <- paste0("S", 1:5)
colnames(phi2) <- paste0("S", 1:5)
phi2["S1","S4"] <- 1
phi2["S2","S5"] <- 1
phi2["S3","S1"] <- 1
phi2["S3","S4"] <- 1
phi2["S3","S5"] <- 1
phi2["S4","S5"] <- 1

phi2 <- phi2 + phi2 %*% phi2
phi2 <- apply(phi2, c(1, 2), function(x) min(x, 1))
phi2
```

## Construction of E-gene attachment matrix

```{r}
theta1 <- matrix(0, nrow=5, ncol=6)
rownames(theta1) <- paste0("S", 1:5)
colnames(theta1) <- paste0("E", 1:6)
theta1["S2", "E4"] <- 1
theta1["S2", "E6"] <- 1
theta1["S3", "E1"] <- 1
theta1["S3", "E2"] <- 1
theta1["S4", "E3"] <- 1
theta1["S5", "E5"] <- 1
theta1
```

```{r}
theta2 <- matrix(0, nrow=5, ncol=6)
rownames(theta2) <- paste0("S", 1:5)
colnames(theta2) <- paste0("E", 1:6)
theta2["S1", "E1"] <- 1
theta2["S1", "E2"] <- 1
theta2["S2", "E4"] <- 1
theta2["S2", "E6"] <- 1
theta2["S4", "E3"] <- 1
theta2["S5", "E5"] <- 1
theta2
```

## Determining effect patterns

```{r}
F1 <- phi1 %*% theta1
F1
```

```{r}
F2 <- phi2 %*% theta2
F2
```

## Discrete data matrix (noiseless)

```{r}
D1 <- t(F1)
D1
```

```{r}
D2 <- t(F2)
D2
```

Given only the data, the two models cannot be told apart.

```{r, eval=FALSE}
library(rmarkdown)
render("NEM.Rmd", pdf_document(TRUE), "Indilewitsch_Toidze_Houhamdi_Pudziuvelyte_Project8.pdf")
```
